inject_layer_number:
  2:
    probability: 1.0
    fault_type: BitFlip
    elements: random
  1:
    probability: 1.0
    fault_type: BitFlip
    elements: all
  3:
    probability: 1.0
    fault_type: BitFlip
    elements: random
  4:
    probability: 1.0
    fault_type: BitFlip
    elements: random
